In [9]:
num=int(input("enter your number here"))
count=0
for i in range(1,num+1):
    if (num%i)==0:
      count = count + 1
if count==2:
    print(prime)
else:
    print("not a prime")

enter your number here 1


not a prime


In [11]:
text="python programming"
vovels="aeiou"
count=0

for i in text:
    if i.lower() in vovels:
        count=count+1
print(f"no of vovels in given text is {count}")

no of vovels in given text is 4


In [ ]:
num=int(input("enter your number here"))
count=0
for i in range(1,num+1):
    if (num%i)==0:
        count=count+1
if count == 2:
    print("prime number")
else:
    print("not prime")

In [2]:
text="enviornmentliists"
vovels="aeiou"
count=0
for i in text:
    if i.lower() in vovels:
        count=count+1

print(f"vovels in the given text as {count}")

vovels in the given text as 6


In [3]:
text="aaeeiioouunilesh"
vovels="aeiou"
for i in text:
    if i.lower()in vovels:
        count=count+1
print(f"vovels in the given text as {count}")

vovels in the given text as 18


In [2]:
num=5
fact=1
for i in range(1,6):
       fact=fact*i
print(fact)

120


In [5]:
num=int(input("enter your num here"))
count=0
for i in range(1,num+1):
    if (num%i)==0:
        count=count+1
if count==2:
    print("prime")
else:
    print("non prime")

enter your num here 2


prime


In [7]:
text="ddbfvkybksfvleintoveo"
vovels="aeiou"
for i in text:
    if i.lower() in vovels:
        count=count+1
print(f"vovels in the given text as {count}")

vovels in the given text as 7


In [11]:
num=int(input("enter your number here"))
count=0
for i in range(1,num+1):
    if (num%i)==0:
        count=count+1
if count==2:
    print("number is prime")
else:
   print("not prime")

enter your number here 2


number is prime


In [14]:
num=int(input("enter your number here"))
count=0
for i in range(1,num+1):
    if (num%i)==0:
        count=count+1
        
    if count==2:
        print(f"number is prime")
        
        
    else:
        print(f"not a prime number")
        
    
    

enter your number here 6


not a prime number
number is prime
not a prime number
not a prime number
not a prime number
not a prime number


In [4]:
text="oirufpwjflsieufouwofjsldnksieh"
vovels="aeiou"
for i in text:
    if i.lower()in vovels:
        count=count+1
print(f"vovels in the given text as {count}")

vovels in the given text as 15


In [17]:
# if meter reading is less than 100

reading=int(input("enter your unit reading here"))

if reading<=100:
    print(f"your bill is {reading*10}rs")
    
elif reading>100 and reading>=200:
    print(f"your bill is {reading*12}rs")
elif reading>200 and reading>=250:
    print(f"your bill is {reading*15}rs")

enter your unit reading here 456


your bill is 5472rs


In [15]:
reading=int(input("enter your unit reading here"))

if reading<=100:
    print(f"your bill is {reading*10}rs")
elif reading>100 and reading<=200:
    print(f"your bill is {1000+((reading-100)*12)} rs")
elif reading>200:
    print(f"your bill is {2200+((reading-200)*15)}rs")

enter your unit reading here 312


your bill is 3880rs


In [6]:
text="yeorituoeirutowteoruwoeiuroiwuery"
vovels="aeiou"
count=0

for i in text:
    if i.lower()in vovels:
        count=count+1
print(f"vovels in the given text as {count}")

vovels in the given text as 20


In [8]:
text="owueyrowyeiyywowieyioweyt"
vovels="aeiou"
count=0
for i in text:
    if i.lower()in vovels:
        count=count+1
print(f"vovels in the given test as {count}")

vovels in the given test as 12


In [7]:
text="yeorituoeirutowteo"
vovels="aeiou"
count=0

for i in text:
    if i.lower()in vovels:
        count=count+1
print(f"vovels in the given text as {count}")

vovels in the given text as 11


In [1]:
text="aeeiioouuytyty"
vovels="aeiou"
count=0

for i in text:
    if i.lower()in vovels:
        count=count+1
print(f"vovels in the given text as{count}")

vovels in the given text as9


In [2]:
value=input("Enter your word here")

if value.lower()==value[::-1].lower():
    print(f"Its a pallindrome")

else:
    print(f"its not a pallindrome")


Enter your word here Nilesh


its not a pallindrome


In [3]:
value1=input("enter your word")
value2=input("enter your word")

if sorted(value1)==sorted(value2):
    print("anagram")
else:
    print("not an anagram")
    

enter your word Nilesh
enter your word Nilesh


anagram


In [4]:
x="string"
print(x[::-1])

gnirts


In [5]:
print("x")

x


In [6]:
x="string"
print(x[::-1])

gnirts


In [21]:
import datetime

In [25]:
datetime.date.today()

datetime.date(2026, 3, 13)

In [27]:
reading=int(input("enter your unit reading here"))

if reading<=100:
    print(f"your bill is {reading*10}rs")
    
elif reading>100 and reading>=200:
    print(f"your bill is {reading*12}rs")
elif reading>200 and reading>=250:
    print(f"your bill is {reading*15}rs")

enter your unit reading here 45646


your bill is 547752rs


In [1]:
a=3
a

3

In [2]:
a

3

In [3]:
print(a)

3


In [4]:
type(a)

int

In [11]:
import datetime

In [12]:
datetime.date.today()


datetime.date(2026, 3, 14)

In [15]:
datetime.datetime.now()

datetime.datetime(2026, 3, 14, 11, 51, 28, 601864)

In [16]:
from datetime import datetime

In [8]:
num=int(input("Enter your text here"))
count=0
for i in range(1,num+1):
    if (num%i)==0:
        count=count+1
if count==2:
    print("its a prime number")
else:
    print("not a prime number")

Enter your text here 2


its a prime number


In [31]:
text="proitperutwuoeprieprtiiioioiip"
vovels="aeiou"
count=0
for i in text:
    if i.lower()in vovels:
        count=count+1
print(f"vovels in the given text as {count}")
        

vovels in the given text as 17


In [1]:
i=1
while i<20:
    if i%2==0:
        print(f"{i} is even")
   
    i=i+1

2 is even
4 is even
6 is even
8 is even
10 is even
12 is even
14 is even
16 is even
18 is even


In [49]:
i=1
while i<11:
    if i%2==0:
        print(f"{i}is even")
    i=i+1

2is even
4is even
6is even
8is even
10is even


In [54]:
add=0
for i in range(1,50):
    add=add+i
print(add)

1225


In [57]:
add=0
for i in range (1,11):
    add=add+i
print(add)

55


In [60]:
num=123
reverse=0
while num>0:
    rem=num%10
    reverse=reverse*10+rem
    num=num//10
print(reverse)

321


In [ ]:
num=123456
reverse=0
while num>0:
    rem=num%10
    reverse=reverse*10+rem
    num=num//10
print(reverse)

In [7]:
# how to find if some one is eligible for wote or not




name=input("enter your name")
age=int(input("enter your age"))
if age>=18:
    voter_id=input("Do you have voter id").lower()
    if voter_id=="yes":
        print(f"you are eligible for voting")
    
    else:
        print(f"please apply for voter id")
   

else:
    print(f"Hellow {name} you are eligible for wote after {18-age} years")

enter your name Nilesh
enter your age 18
Do you have voter id YES


you are eligible for voting


In [23]:
# how to give grades based on markes  
marks=int(input("enter your marks here"))
if marks>=90 and marks<=100:
    Grade="A"
elif marks>=80 and marks<90:
    Grade="B"
elif marks>=70 and marks<80:

    Grade="C"
else:
    Grade="Fail"

print(f"your score is {Grade}")

enter your marks here 95


your score is A


In [8]:
name=input("enter your name here")
age=int(input("enter your age"))

if age>=18:
    Driving_liscence=input("Do you have driving liscence")
    if Driving_liscence=="yes":
        print("You are eligible for drive")
    elif Driving_liscence=="no":
        print("please apply for driving liscence")
    else:
        print("please provide valid input")

else:
    print(f"Hellow {name} you are eligible for driving liscence after {18-age} years")

enter your name here Nileah
enter your age 15


Hellow Nileah you are eligible for driving liscence after 3 years


In [1]:
nums=[7,2,9,89,456]
target=9

def two_sum(num,target):
    dict1={}
    for i,num in enumerate(nums):
        diff=target-1
    

In [22]:
from datetime import datetime

name=input("enter your name here")
birth_year=int(input("*enter your birth year here"))



current_year = datetime.now().year


age = current_year - birth_year

print(f"Hello {name} you are {age} years old")

enter your name here Nilesh
*enter your birth year here 1997


Hello Nilesh you are 29 years old


In [23]:
from datetime import datetime

name=input("Enter your  name here")
Birth_year=int(input("Enter your birth year here"))

current_year=datetime.now().year

age = current_year-Birth_year

print(f"Hello {name} you are {age} years old")

Enter your  name here Nilesh
Enter your birth year here 1997


Hello Nilesh you are 29 years old


In [7]:
from datetime import datetime

name=input("Enter your name here")
Birth_year=int(input(f"Enter your date of birth"))

current_age=datetime.now().year

age=Birth_year-current_age

print(f"Hello {name} you are {age} years old")

Enter your name here Madan
Enter your date of birth 1976


Hello Madan you are -50 years old


In [6]:
name=input("Enter your name")
age=int(input("enter your age here"))

if age>=18:
    Driving_liscence=input("do you have a driving liscence")
    if Driving_liscence=="yes":
        print(f"Hello {name} you are eligible to  drive")
    elif Driving_liscence=="no":
        print("Please apply for a driving liscence")
    
    else:
        print("Please, provide a valid input")

else:
    print(f"Hello {name} you are eligible for driving liscence after {18-age} years")
    

Enter your name Madan
enter your age here 10


Hello Madan you are eligible for driving liscence after 8 years


In [16]:
def loop(x):
    add=0
    for i in range(1,x):
        add=add+i
    return add

In [20]:
x=(16,20)

# Questions given by data mights   on 20/03/2026

In [ ]:
#Print "Hello, Python" on the screen.

print("Hello   python")

In [ ]:
#2.	Store your name in a variable and print it.
x= ("Nilesh")

In [ ]:
x

In [5]:
#Take a number as input and print its square.

x=int(input("Enter a number"))

print(x*x)

Enter a number 6


36


In [8]:
#Write a program to add two numbers

x=int(input("Enter a number"))
y=int(input("Enter a number"))

print(x+y)

Enter a number 6
Enter a number 10


16


In [11]:
x=2
y=4
print(x+y)

6


In [12]:
#Find the type of a variable (int, float, str)

type(x)

int

In [91]:
#Check whether a number is even or odd

Num=int(input("Enter a number"))

if (Num%2)==0:
    print("even")
else:
    print("odd")


Enter a number 2


even


In [21]:
#Check whether a number is positive, negative, or zero.

num=int(input("Enter a number"))
if (num>0):
    print("positive")
elif (num<0):
    print("negative")
else:
    print("the number is zero")

Enter a number 0


the number is zero


In [ ]:
#Print "Pass" if marks ≥ 40, else "Fail"

marks=int(input("Enter marks here"))
if marks>=40:
    print("Pass")
else:
    print("Fail")

In [49]:
#Print numbers from 1 to 10 using a for loop.

for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [3]:
#Print even numbers between 1 and 20.

for i in range(1,20):
    if (i%2)!=0:
        print(i)
    

1
3
5
7
9
11
13
15
17
19


In [4]:
add=0
for i in range(1,11):
    add=add+i
print(add)

55


In [ ]:
#print the multiplication table of a given number

num=int(input("Enter a number"))
print(f"multiplication table of {num}")
for i in range(1,11):
    print(f"{num} x {i} = {num*i}")



In [5]:
num=int(input("Enter a number"))
print("multiplication table of {num}")

for i in range(1,11):
    print(f"{num} x {i} = {num*i}")

Enter a number 12324


multiplication table of {num}
12324 x 1 = 12324
12324 x 2 = 24648
12324 x 3 = 36972
12324 x 4 = 49296
12324 x 5 = 61620
12324 x 6 = 73944
12324 x 7 = 86268
12324 x 8 = 98592
12324 x 9 = 110916
12324 x 10 = 123240


In [12]:
count=12321546535
digit=len(str(count))

print(digit)

11


In [24]:
#Write a program to find the largest of two numbers

num1=int(input("enter a number"))
num2=int(input("enter a number"))

if num1>num2:
    print("num1 is greater")
elif num2>num1:
    print("num2 is greater")
else:
    print("both are equel numbers")

enter a number 1
enter a number 1


both are equel numbers


In [38]:
year=int(input("Enter a year"))
if year%4==0:
    print("this is a leap year")
else:
    print("not a leap year")

Enter a year 2033


not a leap year


In [7]:
num=12345678978976541325635421

digit=len(str(num))
print(digit)

26


In [7]:
#Reverse a string

x="Nilesh Dharmadhikari"
print(x[::-1])

irakihdamrahD hseliN


In [12]:
#Check whether a string is a palindrome

value=input("Enter your word")

if value==value[::-1]:
    print("its a palindrome")
else:
    print("not a palindrome")
    

Enter your word madam


its a palindrome


In [17]:
#Count vowels in a string.

text="weuorywoerpowyeroiwue"
vovels="aeiou"
count=0
for i in text:
    if i.lower()in vovels:
        count=count+1
print(f"vovels given in text as {count}")

vovels given in text as 11


In [18]:
text="owueortueoriytoeurtouiyroiyouyoiy"
vovels="aeiou"
count=0
for i in text:
    if i.lower()in vovels:
        count=count+1
print(f"vovels in the givem text  as {count}")

vovels in the givem text  as 20


In [19]:
#	Convert a string to uppercase

x="nilesh"
print(x.upper())

NILESH


In [22]:
#	Create a list of 5 numbers and print it.

x=["nil,dha,rma,agri"]
print(x)

['nil,dha,rma,agri']


In [23]:
x

['nil,dha,rma,agri']

In [26]:
N=[12,65,23,6,321]
N

[12, 65, 23, 6, 321]

In [27]:
N

[12, 65, 23, 6, 321]

In [28]:
#Find the maximum and miimum from a list.
List=[32,56,654,789,312]

max(List)

789

In [29]:
min(List)

32

In [32]:
#Find the sum of elements in a list.

list=[21,12,32,65,45,78,98,546]
sum(list)

897

In [3]:
#Count how many times an element appears in a list.

list=[21,21,2,3,5,4,21,21,21,2]
count=list.count(21)
print(count)


5


In [9]:
#Sort a list in ascending order

list=[2,2,5,4,1,3,6,4,9,8,7,]

list.sort()

In [4]:
list

[1, 2, 2, 3, 4, 4, 5, 6, 7, 8, 9]

In [3]:
#Write a function to add two numbers.

def add(x,y):
    return x+y

In [4]:
add(60,156)

216

In [16]:
#Write a function to check if a number is prime.

num=int(input("Enter a number"))
count=0
for i in range(1,num+1):
    if (num%i)==0:
        count=count+1
if count==2:
    print("Prime number")
else:
    print("Not a prime number")

Enter a number 2


Prime number


In [23]:
# Cell 1: Define a function to check prime numbers from 1 to 100.
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True
primes = [num for num in range(1, 101) if is_prime(num)]
print("Prime numbers between 1 and 100 are:")
print(primes)

Prime numbers between 1 and 100 are:
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [24]:
#Write a function to return square of a number.

def square(n):
    return(n*n)



In [29]:
square(9)

81

In [54]:
def name():
    return("Nilesh")

In [55]:
name()

'Nilesh'

In [56]:
def name():
    print("Copilot")

# Example usage:



In [57]:
name()

Copilot


In [1]:
def name():
    return("Hellow Nilesh")

In [3]:
name()

'Hellow Nilesh'

# Python Numpy

In [5]:
#topics
#Numpy package overview
#importing Numpy
#Numpy arrays
#Numpy essentions arrange,reshape, zeros, floos,vstalk,hstalk

In [5]:
import numpy as np

In [7]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [11]:
b = np.arange(20)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
b = np.arange(20)
b.ndim

1

In [22]:
d= np.arange(100).reshape(10,10)
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [27]:
g = np.arange(9).reshape(3,3)
g

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
h = np.arange(12).reshape(4,3)
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
np.vstack((g,h))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
i = np.arange(9).reshape(3,3)
j = np.arange(12).reshape(3,4)
print(i)
j

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
np.hstack((i,j))

array([[ 0,  1,  2,  0,  1,  2,  3],
       [ 3,  4,  5,  4,  5,  6,  7],
       [ 6,  7,  8,  8,  9, 10, 11]])

In [37]:
np.random.random()

0.7501927984687176

In [7]:
k = np.random.random((2,5))
k

array([[0.57706719, 0.99904733, 0.84433794, 0.81655418, 0.48892697],
       [0.69763595, 0.40592001, 0.08358325, 0.97734371, 0.03719774]])

In [6]:
l = np.floor(100*np.random.random((2,5)))
l

array([[32., 65., 32., 95., 74.],
       [64., 34., 39.,  6., 74.]])

In [10]:
np.floor((10.4))

np.float64(10.0)

In [11]:
np.ceil(10.4)

np.float64(11.0)

In [1]:
# prime number

In [12]:
num = int(input("Enter a number"))
count=0
for i in range(1,num+1):
    if (num%i)==0:
        count=count+1
if count==2:
    print("prime")
else:
    print("Non a prime")

Enter a number 32


Non a prime


In [16]:
text = "pouoyitiuopiutytyuoipopuotyryuiop"
vovels = "aeiou"
count = 0
for i in text:
    if i.lower()in vovels:
        count=count+1

print(f" No of vovels in the given text is {count}")
    

 No of vovels in the given text is 18


In [18]:
marks = int(input("Enter your marks here"))

if marks >= 90:
    print("A grade")
elif marks > 80 and marks<90:
    print(" B grage")

Enter your marks here 85


 B grage


In [28]:
num = int(input(" Enter a num here"))

for i in range(1,11):
    print(f"{num} x {i} = {num*i}")

 Enter a num here 6


6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
6 x 10 = 60


In [49]:
reading = int(input("Enter your reading here"))



if reading>100:
    print(f"your bill is {reading*10}")
    if reading>90 and reading<100:
        print(f"your bill is {reading*8}")

else:
    print(f"your bill is {reading*5}")

Enter your reading here 135435


your bill is 1354350


In [57]:
name = input("Enter your name")
age = int(input("Enter your age"))
if age>18:
    Driving_liscence= input("Do you have a driving liscence")
    if Driving_liscence=="yes":
        print("You are elegible to drive")
    elif Driving_liscence=="no":
        print("Please apply for a liscence")
    else:
        print(f"Please enter a valid input")
else:
    print(f"you are elegible to drive after {18-age}")


Enter your name 28
Enter your age 28
Do you have a driving liscence ljjkjbv


Please enter a valid input


In [62]:
str = "Nilesh"
print(str[::-1])

hseliN


In [70]:
num = int(input("Enter a number"))
if num>0:
    print("num is positive")
if num<0:
    print("negative")
elif num==0:
    print("Zero")


Enter a number -5


negative


In [74]:
text = "Nilesh dharmadhikari"
digit=len(text)
print(digit)

20


In [93]:
num =int(input("Enter a number"))

if (num%2)==0:
    print("Even")
else:
    print("Odd")

Enter a number 1


Odd


In [101]:
list = [1,2,3,4,5,6,1,2,3,1,1,1,1,2,1,23,,2,1,1,1,1,1]
count=list.count(a)
print(count)
    

NameError: name 'a' is not defined

In [6]:
inventory = {
    "apple": 50,
    "banana": 20,
    "orange": 54,
    "mango": 15
}

def add_stock(item, quantity):
    """Add stock for an item."""
    if item in inventory:
        inventory[item] += quantity
    else:
        inventory[item] = quantity

def sell_item(item, quantity):
    """Sell items without exceeding available stock."""
    if item not in inventory:
        print(f"{item} not found in inventory.")
        return
    if quantity > inventory[item]:
        print(f"Cannot sell {quantity} {item}(s). Only {inventory[item]} available.")
    else:
        inventory[item] -= quantity
        print(f"Sold {quantity} {item}(s). Remaining: {inventory[item]}")

def out_of_stock_items():
    """Return a list of items that are out of stock."""
    return [item for item, qty in inventory.items() if qty == 0]

def sorted_inventory():
    """Return inventory sorted by quantity (highest first)."""
    return dict(sorted(inventory.items(), key=lambda x: x[1], reverse=True))

In [7]:
add_stock("apple", 10)
sell_item("banana", 4)
print("Out of stock:", out_of_stock_items())
print("Sorted inventory:", sorted_inventory())

Sold 4 banana(s). Remaining: 16
Out of stock: []
Sorted inventory: {'apple': 60, 'orange': 54, 'banana': 16, 'mango': 15}


In [15]:
inventory = {"apple": 50,"banana": 20,"orange": 54,"mango": 15}

def add_stock(items,quantity):
    if items in inventory:
        inventory [items] += quantity
    else:
        inventory [items] = quantity
def sell_items(items,quantity):
    if item not in inventory:
        print(f"{items} not available.")
    if quqntity > inventory [items]:
        print(f"cannot sell {quantity} {items}. remaining: {inventory[items]} available")
    else:
        inventory[items]-= quantity
        print(f"sold {quantity} {items}(s). remaining {inventory[item]}")

def sorted_inventory():
    return dict(sorted(inventory.items(),key=lambda x: x[1], reverse= True))

In [18]:
add_stock("banana",400)
sorted_inventory()

{'banana': 1220, 'orange': 54, 'apple': 50, 'mango': 15}

In [ ]:
s

In [1]:
# reverse a string 

x= "Nilesh"

print(x[::-1])

hseliN


In [6]:
def rev_str(x):
    return x[::-1]
    

In [7]:
rev_str("NILESH DHARMADHIKARI")

'IRAKIHDAMRAHD HSELIN'

In [13]:
def factorial(n):
    if n==0 or n == 1:
        return 1
    return n * factorial(n-1)

In [20]:
factorial(9)

362880

In [37]:
def pal(p):
    print(p==p[::-1])

In [40]:
pal("madam")

True


In [ ]:
### write a person is eligible to wote or not

name =(input("enter nour name"))
age = int(input("enter  your age"))
if age>18:
    voter_id= input("do you have a voter id card").lower()
    
    if voter_id=="yes":
        print("you are eligible to vote")
    else:
        print("please apply for voter id")
else:
    print(f"you are eligible to wote after{18-age}years")

In [3]:
name=input("enter your name")
age=int(input("enter your age"))
if age>=18:
    voter_id=input("Do you have voter id").lower()
    if voter_id=="yes":
        print(f"you are eligible for voting")
    elif voter_id=="no":
         print(f"please apply for voter id")
    
    else:
       print(f"please give a valid input")
    
    
else:
    print(f"Hellow {name} you are eligible for wote after {18-age} years")

enter your name nil
enter your age 20
Do you have voter id dfv


please give a valid input


In [2]:
num= int(input("enter your number"))

if num%2==0:
    print("even")
else:
    print("odd")

enter your number 1


odd


In [7]:
num=[1,2,3,4,54,87,987,4564,45,10]

largest = max(num)
smallest = min(num)

print("Numbers", num)
print("largest number", largest)
print("smallest number", smallest)

Numbers [1, 2, 3, 4, 54, 87, 987, 4564, 45, 10]
largest number 4564
smallest number 1


In [9]:
text = "Nilesh"

reversed_text = "".join(reversed(text))

print("reversed string", reversed_text)

reversed string hseliN


In [12]:
text = "dharmadhikari"

reversed_string = "".join(reversed(text))
print(reversed_string)

irakihdamrahd


In [4]:
text = "Siddharth"

print(text[::-1])

htrahddiS


In [6]:
x = "i am a man"
vovels = "aeiou"
count=0
for i in x:
    if i in vovels:
        count=count+1

print(f"vovels in the given sentense {count}")

vovels in the given sentense 4


In [8]:
def sum_of_even(numbers):
    return sum([num for num in numbers if num %2 == 0])

sum_of_even(1,123)

In [9]:
def sum_of_even(numbers):
    count = 0
    for num in numbers:
        if num%2 == 0:
            count+= num
    return count





In [11]:
nums = [12,7,9,4,18,21,6,11]
print(sum_of_even(nums))

40
